include:
  - docker-compose.infra.yml
  - docker-compose.apps.yml
  - docker-compose.monitoring.yml
  - docker-compose.media.yml
  - path: docker-compose.sparky.yml
    env_file: .env.sparky

networks:
  internal:
    name: olympus_internal
    driver: bridge